#!/bin/bash

perl twiki2pod.pl a.twiki \
    | pod2text -u -i 1 -w 69 - \
    | perl -e '$s = do { local $/; <> }; $s =~ s/(<http[^>]+)\n\s+([^>]+?>)/$1$2/g; print $s' \
    | sed 's/\<LuaNginxModule\>/the ngx_lua module/' \
    | sed 's/\<SrcacheNginxModule\>/the ngx_srcache module/' \
    | sed 's/\<LuaRestyCoreLibrary\>/the lua-resty-core library/' \
    | sed 's/\<LuaRestyUpstreamHealthcheckLibrary\>/the lua-resty-upstream-healthcheck library/' \
    | sed 's/\<LuaRestyDNSLibrary\>/the lua-resty-dns library/' \
    | sed 's/\<LuaRestyLrucacheLibrary\>/the lua-resty-lrucache library/' \
    | sed 's/\<EchoNginxModule\>/the ngx_echo module/' \
    | sed 's/\<MemcNginxModule\>/the ngx_memc module/' \
    | sed 's/\<FormInputNginxModule\>/the ngx_form_input module/'


