#!/bin/bash

perl twiki2pod.pl a.twiki \
    | pod2text -u -i 1 -w 69 - \
    | perl -e '$s = do { local $/; <> }; $s =~ s/(<http[^>]+)\n\s+([^>]+?>)/$1$2/g; print $s' \
    | sed 's/\<LuaNginxModule\>/the ngx_lua module/' \
    | sed 's/\<SrcacheNginxModule\>/the ngx_srcache module/' \
    | sed 's/\<LuaRestyCoreLibrary\>/the lua-resty-core library/' \
    | sed 's/\<LuaRestyLrucacheLibrary\>/the lua-resty-lrucache library/' \

