#!/bin/bash

perl twiki2pod.pl a.twiki \
    | pod2text -u -i 1 -w 69 - \
    | perl -e '$s = do { local $/; <> }; $s =~ s/(<http[^>]+)\n\s+([^>]+?>)/$1$2/g; print $s' \
    | sed 's/\<LuaNginxModule\>/the ngx_lua module/' \
    | sed 's/\<SrcacheNginxModule\>/the ngx_srcache module/' \
    | sed 's/\<LuaRestyCoreLibrary\>/the lua-resty-core library/' \
    | sed 's/\<LuaCjsonLibrary\>/the lua-cjson library/' \
    | sed 's/\<LuaRestyUpstreamHealthcheckLibrary\>/the lua-resty-upstream-healthcheck library/' \
    | sed 's/\<LuaRestyDNSLibrary\>/the lua-resty-dns library/' \
    | sed 's/\<LuaRestyWebSocketLibrary\>/the lua-resty-websocket library/' \
    | sed 's/\<LuaRestyMySQLLibrary\>/the lua-resty-mysql library/' \
    | sed 's/\<LuaRestyLrucacheLibrary\>/the lua-resty-lrucache library/' \
    | sed 's/\<LuaRestyLockLibrary\>/the lua-resty-lock library/' \
    | sed 's/\<EchoNginxModule\>/the ngx_echo module/' \
    | sed 's/\<DrizzleNginxModule\>/the ngx_drizzle module/' \
    | sed 's/\<CoolkitNginxModule\>/the ngx_coolkit module/' \
    | sed 's/\<SetMiscNginxModule\>/the ngx_set_misc module/' \
    | sed 's/\<PostgresNginxModule\>/the ngx_postgres module/' \
    | sed 's/\<MemcNginxModule\>/the ngx_memc module/' \
    | sed 's/\<Redis2NginxModule\>/the ngx_redis2 module/' \
    | sed 's/\<FormInputNginxModule\>/the ngx_form_input module/'

